/* seahorse-gkr.h generated by valac 0.18.1, the Vala compiler, do not modify */


#ifndef __SEAHORSE_GKR_H__
#define __SEAHORSE_GKR_H__

#include <glib.h>
#include <stdlib.h>
#include <string.h>

G_BEGIN_DECLS



#define SEAHORSE_GKR_NAME "gkr"


G_END_DECLS

#endif
