include: 'https://gitlab.gnome.org/GNOME/citemplates/raw/master/flatpak/flatpak_ci_initiative.yml'

stages:
- test
- deploy

variables:
  BUNDLE: 'seahorse.flatpak'

flatpak:
  image: registry.gitlab.gnome.org/gnome/gnome-runtime-images/gnome:master
  variables:
    MANIFEST_PATH: 'build-aux/org.gnome.Seahorse.json'
    MESON_ARGS: ""
    FLATPAK_MODULE: "seahorse"
    RUNTIME_REPO: "https://nightly.gnome.org/gnome-nightly.flatpakrepo"
    APP_ID: "org.gnome.SeahorseDevel"
  extends: .flatpak

review:
  stage: deploy
  dependencies:
    - flatpak
  script:
    - echo "Generating flatpak deployment"
  extends: '.review'

stop_review:
  stage: deploy
  script:
    - echo "Stopping flatpak deployment"
  extends: '.stop_review'

nightly:
  extends: '.publish_nightly'
