include: 'https://gitlab.gnome.org/GNOME/citemplates/raw/master/flatpak/flatpak_ci_initiative.yml'

variables:
  BUNDLE: 'seahorse.flatpak'

flatpak:
  image: registry.gitlab.gnome.org/gnome/gnome-runtime-images/gnome:master
  variables:
    MANIFEST_PATH: 'build-aux/org.gnome.seahorse.ApplicationDevel.json'
    MESON_ARGS: "-Dprofile=development"
    FLATPAK_MODULE: "seahorse"
    RUNTIME_REPO: "https://nightly.gnome.org/gnome-nightly.flatpakrepo"
    APP_ID: "org.gnome.seahorse.ApplicationDevel"
  extends: .flatpak

nightly:
  extends: '.publish_nightly'
  dependencies: ['flatpak']
  needs: ['flatpak']
