.\"
.\" This page was created on 2006-05-06 19:28:06 by makeman.pl
.\" ``makeman.pl'' is part of the ``MakeMan'' project.
.\" For more information, please see http://mama.sourceforge.net
.\"
.TH seahorse\-daemon 1 "May 04, 2006" "seahorse" "GNOME" 

.SH NAME
seahorse\-daemon \- seahorse pass phrase caching agent

.SH SYNOPSIS
\fBseahorse\-daemon\fR
[ \fIOPTION\fR... ] 

.SH "DESCRIPTION"
.PP
Seahorse is a GNOME application for managing encryption keys. 
.PP
This is the agent program for seahorse which keeps a temporary secure
storage of your pass phrases. It also works with the SSH agent to prompt
you for SSH passphrases.

.SH "OPTIONS"

.SS "Help options"
.\" Begin List
.TP
\fB\-?, \-\-help\fR
Show summary of all options and exit.
.TP
\fB\-\-usage\fR
Display brief usage message and exit.
.\" End List

.SS "Application options"
.\" Begin List
.TP
\fB\-c, \-\-cshell\fR
Print variables in for a C type shell.
.TP
\fB\-d, \-\-no\-daemonize\fR
Do not daemonize seahorse\-daemon.
.TP
\fB\-\-v, \-\-variables\fR
Display variables instead of editing gpg.conf.
.\" End List

.SS "Additional options"
.PP
In addition, the usual GTK+ and GNOME command line options apply. See the output of \-\-help for details.

.SH "VERSION"
.PP
This man page describes \fBseahorse\-daemon\fR version 0.9.

.SH "BUGS"
.PP
If you find a bug, please report it at 
 \fIhttp://bugzilla.gnome.org/enter_bug.cgi?product=seahorse\fR.

.SH "AUTHORS"
.PP
Jacob
Perkins
<jap1@users.sourceforge.net>
.PP
Jose Carlos Garcia
Sogo
<jsogo@users.sourceforge.net>
.PP
Jean
Schurger
<jk24@users.sourceforge.net>
.PP
Nate
Nielsen
<nielsen@memberwebs.com>
.PP
Adam
Schreiber
<sadam@clemson.edu>
.PP
This man page was originally written by
Michael
Mende
<debian@menole.net>
for the Debian system.

.SH "COPYRIGHT"
.PP
.br
Copyright (C) 2001, 2002 Jose Carlos Garcia Sogo
.br
Copyright (C) 2002, 2003 Jacob Perkins
.br
Copyright (C) 2004, 2006 Nate Nielsen, Adam Schreiber

.SH "LICENSE"
.PP
.br
You are free to distribute this software under the terms of the GNU General Public License.
.br
Documentation and help files are covered by GFDL license.

.SH "SEE ALSO"
.PP
\fBseahorse-tool(1)\fR,
\fBseahorse-daemon(1)\fR
